Add Support For Symfony 7.0
RamyHakam/multi_tenancy_bundle pull request #30
Opened 2024-01-28 22:54 UTC by Galironfydar

2024-02-17 20:47 UTC, RamyHakam commented
Hey @Galironfydar  Thanks for your PR 
I have some general comments on your PR 
1. Can you Please split your PR in 2, Cuz this PR has 2 different tasks For example you can split them to :
      **One for Symfony 7 Support**
     **One for Delete Comment** 
2. Deleting tenant DB only will not work  in this approach you need to have a safe clean 
, Cuz it has a relation with the tenant user config which is the tenant user for this database 
So If you want to add this command you need to delete the tenant user config and then delete the db config 
Please see the example repo for that [multi-tenancy-project-example](https://github.com/RamyHakam/multi-tenancy-project-example)
Also deleting Tenant DB is a critical command that should not be available on the prod 
you can restrict this command only on the dev env use this function in your command 
`   public function isEnabled(): bool
    {
        return 'dev' === getenv('APP_ENV');
    }`

2024-02-17 20:49 UTC, RamyHakam requested changes

2024-02-17 20:49 UTC, RamyHakam commented on src/Services/DbService.php
> +        return $this->entityManager->getRepository($this->tenantDbListEntity)->findOneBy(['dbName' => $databaseName]);
You do not use `$id` in this function, Also `$databaseName` not exist

2024-02-20 16:28 UTC, Galironfydar commented
Apologies, the tenant deletion stuff was me playing around, I'll create another pull request for that, I've just removed it.

2024-02-26 19:19 UTC, NikoGrano commented
@RamyHakam Changes look good to me, would you mind merging and creating the release for the composer? This is currently a blocker for me to upgrade 7.x.

Thanks for all your work!

2024-02-26 19:19 UTC, NikoGrano approved these changes

2024-02-26 20:24 UTC, RamyHakam approved these changes

2024-02-26 20:24 UTC, merged